name: Upload to YouTube

on:

  workflow_dispatch:

  repository_dispatch:
    types: social_exporter_webhook

env:

  VIDEO_URL: ${{ github.event.client_payload.VIDEO_URL }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout this repo
        uses: actions/checkout@v2

      - name: download video from url
        run: |
            wget -O ./video.mp4 ${{ env.VIDEO_URL }} 


      - name: Setup YouTube Uploader
        uses: AnimMouse/setup-youtubeuploader@v1
        with:
          client_secrets: ${{ secrets.CLIENT_SECRETS_B64 }}
          request_token: ${{ secrets.REQUEST_TOKEN_B64 }}


      - name: Run YouTube Uploader
        run: |
            youtubeuploader \
              -debug \
              -secrets $RUNNER_TEMP/client_secrets.json \
              -cache $RUNNER_TEMP/request.token \
              -filename video.mp4  \
              -metaJSON metadata.json   \
              -metaJSONout metaout.json \


      - name: output metadata returned
        run: |
            cat metaout.json